import os

env = Environment(CC='g++',CCFLAGS=Split("-std=c++17 -pthread"))

cpppath=["./", "/usr/local/include/"]
env.Append(CPPPATH = cpppath)

libpath=["/usr/local/lib"]
env.Append(LIBPATH = libpath)

libs = ["gtest", "gtest_main"]
env.Append(LIBS = libs)

Export("env")

def FindSrc():
    srcs = []
    for path in cpppath:
       for file in os.listdir(path):
           if file[-3:] == ".cc" or file[-4:] == ".cpp":
               srcs.append(path + "/" + file)
    return srcs

env.Program(target="prog", source=FindSrc())
#env.Library(target="prog.a", source=FindSrc())
#env.SharedLibrary(target="prog.so", source=FindSrc())
