#!/usr/local/bin/bash
# g++ -std=c++11 -I /usr//local/include/boost -I /opt/OpenBLAS/include -L /opt/OpenBLAS/lib/ -lopenblas $1
g++ -std=c++11 -I /usr//local/include/boost $1
./a.out
/bin/rm -f a.out
