import os
env = Environment(CC="g++", CCFLAGS="-std=c++11")

env.Program("main", "main.cpp")
env.Program("ShellSort", "ShellSort.cpp")
env.Program("HeapSort", "HeapSort.cpp")
env.Program("BubbleSort.cpp")
env.Program("HeapSort.cpp")
env.Program("InsertSort.cpp")
env.Program("MergeSort.cpp")
env.Program("QuickSort.cpp")
env.Program("RadixSort.cpp")
env.Program("SelectionSort.cpp")
env.Program("ShellSort.cpp")
